spring.application.name=mask
server.port=8082

jwt.secret=${JWT_SECRET:ChangeThisSecretKeyToSomethingSecureAndAtLeast32BytesLong!}
jwt.expiration-ms=3600000

jwt.users-secret=${JWT_USERS_SECRET:Gy5yK/3cjXD529NdyhP+v1VK8N92JItc/YqAxLFFk5c=}
jwt.users-expiration-minutes=15
